# Generated by Django 3.1.5 on 2021-03-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_books_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
