# Generated by Django 3.1.5 on 2021-04-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210306_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dimensions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
