# Generated by Django 3.1.5 on 2021-04-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_comment_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
